import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { currentUser } from "@clerk/nextjs/server";
import prisma from "@/lib/prisma";
import { randomUUID } from "crypto";
import { ReduxProvider } from "@/store/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser(); // Server-side user
  const id = user?.id;
  const firstName = user?.firstName || "";
  const email = user?.emailAddresses?.[0]?.emailAddress || "";

  if (id && email) {
    // check required fields
    const isUser = await prisma.user.findUnique({
      where: { clerkId: id },
    });

    if (!isUser) {
      await prisma.user.create({
        data: {
          clerkId: id,
          name: firstName,
          email: email,
          lifeId: randomUUID(),
        },
      });
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <ReduxProvider>
            <Navbar />
            {children}
            <Footer />
          </ReduxProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
